### ISSUE TITLE
A custom library for arrays

### ISSUE THREAD

**Issue by SammyUrfen** [Silicon27/EPLRemade#1]
Hello @Silicon27 
I would like to add a custom library that has different types of functions for arrays/list like - swap, reversal, includes an element, count of an element, first index of an element, binary search on the array, array sorting, etc.
I could also make it so that the function lists the steps involved in these functions and thus it will be more helpful to students trying to learn. 
I am a college student myself and I would like to contribute to this repository for Hacktoberfest

**Comment by Silicon27** [comment]
Hey @SammyUrfen!
Yeah, I’m planning on making one too. As I’m mainly focusing on mathematics right now, I’m primarily developing on the math module. But it’ll be great if you could make those algorithms.

I’m thinking, make a folder named `algo`, as in “algorithms”, and put it all into there. Alternatively I’ll add the folder in the next time I’m updating the repo from my local as I’m almost done with adding the next feature.

thanks for reaching out!
